### PR TITLE
Migrate to GitHub Action CI

### LINKED ISSUE #31: Migrate from Travis CI to Github Actions
Travis-CI's new ".com" model has caps on open source builds (bad). This is currently blocking a PR from running more test builds. Migration is relatively simple, I'm testing on another repo and once it works will add here

### PR DESCRIPTION
**Pull request by JWKennington**
# Description

Fixes #31 

Changes:
- Switched to Github Action for free builds
- added windows build

# Testing

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] PR Test Suite

# Examples
Include an example of new features here when applicable

### CODE REVIEW

**Comment by JWKennington** [comment]
Fixing the 3.7 pickle now

**Comment by JWKennington** [comment]
@jacksonhenry3 I got it working in a different repo, so should be quick to standup here. Once the builds pass, you'll need to update the branch rule under Settings > Branches > Rules > main. Uncheck "travis" and check the new ones "Build / UNIX" and "Build / WIN"

**Comment by JWKennington** [comment]
@jacksonhenry3 the build passed! (even fixed the pickle thing you saw, it's likely because you're actually using python 3.7). Can you update the branch rule?

**Comment by jacksonhenry3** [comment]
Ok, I switched it. I included python 3.8 on macos, windows and ubuntu.

**Comment by JWKennington** [comment]
awesome thanks!

**Pull request merged**
