### PR TITLE
Cleanup/space time

### PR DESCRIPTION
**Pull request by jacksonhenry3**
# Description

This breaks move and inverse move! They function on their own, but when used repeatedly they cause keys to try and be used that are no longer valid. This is OK because they will be the focus of the next major update to get them in  line with the new symmetrically modified event object.
 
1. removed generate_flat from space-time class
2. separated move and inverse move from space_time class in to modifications.py
3. Updated inverse move to function with event class.

Fixes # (issue)

Changes:
- change 1

# Testing

running 
```python
size = 10
FST = generate_flat_spacetime(size, size)

n = FST.get_random_node()
f = random.choice(n.future)
p = random.choice(n.past)
move(FST, n, f, p)
n = FST.get_random_node()
imove(FST, n)
display.plot_2d(FST)
```
produces a valid plot with a move and inverse move done. 

If move and inverse move are executed repeatedly then this can fail.

### CODE REVIEW

**Comment by JWKennington** [comment]
This looks good, but is likely to have significant merge conflicts with #18, which I can help resolve. I would have merged #18 already if not for the remaining question of replaced-node consistency (would like your thoughts on the issue)

**Comment by jacksonhenry3** [comment]
You can go ahead and merge #18 and this. I'll do my best moving forward to move quickly on responses and keep my branches semantically distinct and small to avoid this type of hassle. Hopefully we'll be able to keep work more distinct once we have a solid base. Thanks for working with me as I learn this new development model.

**Comment by JWKennington** [comment]
@jacksonhenry3 like I said on #18, no worries! I only learned these things in industry because other people helped me figure them out. These issues will subside once the code structure stabilizes (which should be very soon)

**Comment by JWKennington** [comment]
There's a couple things to resolve in the `move` method, I can take a look later today

**Comment by jacksonhenry3** [comment]
I'd like to get to work on fixing move/imove later today,so if you could let me know what the ETA on this merge it would be helpful for planning. (it seems like it would be causing more problems than it would solve for me to modify this branch further before merge) I have also merged my changes to the visualization structure, hopefully that doesn't cause any additional conflicts.

**Pull request merged**
