### PR TITLE
Fix Move and Inverse Move (**Work in Progress**)

### PR DESCRIPTION
**Pull request by JWKennington**
# Description

Fixes # (issue)

Changes:
- Fix problems in Move / Inverse move
- Added tests for functional inverse of move / inverse move

# Testing

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] PR Test Suite

# Examples
Include an example of new features here when applicable

### CODE REVIEW

**Comment by JWKennington** [comment]
@jacksonhenry3 Here's a stub bit of work for fixing move / imove, which I know you want to do. Drafted this just to check the functional inverse of move / imove now that SpaceTime == actually compares all attributes (no surprise, it failed). I'll stop pushing to this to allow you to fix the move mechanics

**Comment by jacksonhenry3** [comment]
Move and inverse move seem to be working now. I don't see what has broken the "test_to_pickle" but i would like to merge these changes so I can start work on a separate branch with working moves and inverse moves. I can force it through or you can get the pickle test fixed. (unless travis isn't doing builds for us right now, in which case i can just force it through)

**Comment by JWKennington** [comment]
All tests are passing locally for me, perhaps the pickle failure is a Windows problem. I'm almost ready to move the repo to using GitHub Actions, since Travis is throttling free accounts now. Should have a workaround for that soon

**Comment by JWKennington** [comment]
Resolved the build failures in a separate PR #35 , once we merge that all of the building / testing will be resolved. I do need you to update a branch rule though (see #35 for details)

**Comment by JWKennington** [comment]
Ok resolved the merge conflict and figured out why the geometric_inverse is failing (nice implementation btw). I had to add one more check to audit.node_diff, the `faces_containing` attribute. It seems that in the test, the "faces containing" aren't being curated

**Comment by jacksonhenry3** [comment]
you're corrected about faces containing, (as per #33 ) I'd like to fix that when replacing get_faces_containing function with the face_containing dict in it's own branch.

**Comment by jacksonhenry3** [comment]
Most of the remaining test failures are stemming from face_containing. I'm forcing this merge (but leaving this branch active if there is more you'd like to do) to work on face_containing separately.

**Pull request merged**
